#!/bin/bash
MY=`which $0  |xargs ls -l | sed -r "s/.* //g" | sed -r "s/.*->//g"`
BUILD_SYS_DIR=${MY%/*}

if [ $1 ]; then
	INSTALL_TARGET=$1
else
	INSTALL_TARGET=/usr/bin
fi

mkdir -p $INSTALL_TARGET

PWD=`pwd`

ln -s `find $PWD/$BUILD_SYS_DIR/build/sh/ -not -name *.sh -type f` $INSTALL_TARGET
